//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyListDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodConvertersList
    {
        public decimal FromQuantity { get; set; }
        public string FromUnit { get; set; }
        public string FoodName { get; set; }
        public string Equal { get; set; }
        public decimal ToQuantity { get; set; }
        public string ToUnit { get; set; }
    }
}
