//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuyListDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngredientsList
    {
        public int RecipeId { get; set; }
        public int IngredientId { get; set; }
        public int FoodId { get; set; }
        public int MeasurementUnitId { get; set; }
        public string RecipeName { get; set; }
        public decimal Quantity { get; set; }
        public string UnitName { get; set; }
        public string FoodName { get; set; }
        public string DisplayIngredient { get; set; }
    }
}
